# Generated by Django 3.1.5 on 2021-01-30 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenseApp', '0003_auto_20210130_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='username',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=40, null=True, unique=True),
        ),
    ]
