# Generated by Django 3.1.5 on 2021-01-30 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenseApp', '0005_auto_20210130_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='comment',
            field=models.CharField(default='', max_length=40),
        ),
    ]
